lint:
  files_exist:
    - conf/test.config
    - conf/test_full.config
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
nf_core_version: 3.1.0
repository_type: pipeline
template:
  author: "J\xFAlia Mir Pedrol, Laurence Kuhlburger"
  description: Pipeline for the analysis of CRISPR data
  force: false
  is_nfcore: true
  name: crisprseq
  org: nf-core
  outdir: .
  version: 2.3.0
