repository_type: pipeline
lint:
  files_exist:
    # We skip the linting of these files as we have splitted tests between targeted and screening
    - conf/test.config
    - conf/test_full.config
    # We skip this linting because we have not finished exporting to nf-test
    - .github/PULL_REQUEST_TEMPLATE.md
  files_unchanged:
    - lib/NfcoreTemplate.groovy # Introduced a change ahead of the nf-core/tools release
